openapi: 3.0.1
info:
  title: EMS Rest API.
  description: ' https://userdocs.cority.com/articles/#!fordevelopers/tools'
  version: ""
components:
  schemas:
    Authenticate_authenticateInfo:
      type: object
      properties:
        username:
          type: string
          description: The username string.
        password:
          type: string
          description: The password string.
      description: Authenticate info.
