# external-schema.yaml
openapi: 3.0.0
info:
  title: External Schema
  version: 1.0.0

components:
  schemas:
    ExternalObject:
      type: object
      properties:
        externalProperty:
          type: string
